version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5432:5432"
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:25.0.1
    environment:
      KEYCLOAK_ADMIN_PASSWORD: "admin"
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_LOGLEVEL: DEBUG
    command: ['start-dev', '--debug', '--import-realm', '--features=client-policies']
    ports:
      - 8787:8080
